### ISSUE TITLE
Virtual Joystick Does Not Work on Android 

### ISSUE THREAD

**Issue by wedybleeno** [jdolny/Prime-Ball-Controller-Docs#3]
Hello,

I have encountered an issue with the virtual joystick in your asset. While it works perfectly in the Unity Editor, it does not respond to touch input after building the game for Android.

Here are the details:
Unity Version: Unity 6
Android Device: Xiaomi MI A3
Asset Version: Latest

Reproduction Steps:

    Import the asset into a new Unity project.
    Configure the virtual joystick as described in the documentation.
    Build and deploy the game on an Android device.
    Attempt to use the joystick; touch input does not register.

I have verified that touch inputs are enabled and that the Event System is present in the scene. Other UI elements (e.g., buttons) work correctly, but the joystick does not respond.

Could you please advise on how to resolve this issue?

Thank you for your assistance!

**Comment by jdolny** [comment]
Hello,
This is due to a bug with Unity 6.  In Unity 6 the default Application Entry Point has been changed from Activity to GameActivity which appears to be buggy.  You need to switch it back to Activity.

Here is a workaround.

Open Project Settings
Select Player
Select the Android Tab if not already selected
Select Other Settings
Scroll down to application entry point and select Activity and de-select GameActivity

![image](https://github.com/user-attachments/assets/dfb7a515-ed94-499f-8f59-694628e04299)

**Comment by wedybleeno** [comment]
Thank you so much! You can't even imagine how many nerves you saved me. I would have never thought to look for the problem there. Thank you again! Wishing you the best of luck with your projects!
